// Generates thin Claude Code skill adapters in `.claude/skills/` from the
// canonical skills in `.agents/skills/`. Claude Code only discovers project
// skills under `.claude/skills/`, so each adapter copies the canonical
// frontmatter (the discovery surface) and points to the canonical body.
//
// Usage:
//   node .claude/sync-skills.mjs          Write adapters and remove stale ones.
//   node .claude/sync-skills.mjs --check  Exit non-zero if adapters drifted.

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const canonicalRoot = join(repoRoot, ".agents", "skills");
const adapterRoot = join(repoRoot, ".claude", "skills");
const generatedMarker =
  "<!-- Generated by .claude/sync-skills.mjs. Do not edit. -->";

/** Lists directory names so canonical and adapter trees can be compared by skill name. */
function listSkillNames(root) {
  if (!existsSync(root)) return [];
  return readdirSync(root, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

/** Extracts frontmatter verbatim so adapter discovery metadata matches the canonical skill exactly. */
function readFrontmatter(skillFile) {
  const text = readFileSync(skillFile, "utf8").replace(/\r\n/g, "\n");
  const match = /^---\n([\s\S]*?)\n---\n/.exec(text);
  if (!match) throw new Error(`Missing frontmatter: ${skillFile}`);
  return match[1];
}

/** Builds the adapter body; it must stay a pointer so skill content keeps one source of truth. */
function renderAdapter(name) {
  const frontmatter = readFrontmatter(join(canonicalRoot, name, "SKILL.md"));
  return `---
${frontmatter}
---

${generatedMarker}

Read and follow \`.agents/skills/${name}/SKILL.md\` before continuing. That file is the authoritative skill; this adapter only registers it for Claude Code discovery. Resolve any relative paths in it against \`.agents/skills/${name}/\`.
`;
}

/** Reads an existing adapter with normalized line endings so Windows checkouts compare cleanly. */
function readAdapter(name) {
  const file = join(adapterRoot, name, "SKILL.md");
  return existsSync(file)
    ? readFileSync(file, "utf8").replace(/\r\n/g, "\n")
    : undefined;
}

/** Finds generated adapters whose canonical skill was removed; hand-written Claude-only skills are left alone. */
function findStaleAdapters(canonicalNames) {
  return listSkillNames(adapterRoot).filter(
    (name) =>
      !canonicalNames.includes(name) &&
      readAdapter(name)?.includes(generatedMarker),
  );
}

/** Reports drift without writing, for CI and pre-commit verification. */
function check(canonicalNames) {
  const problems = [];
  for (const name of canonicalNames) {
    if (readAdapter(name) !== renderAdapter(name))
      problems.push(`out of date: .claude/skills/${name}/SKILL.md`);
  }
  for (const name of findStaleAdapters(canonicalNames))
    problems.push(`stale: .claude/skills/${name}/`);
  if (problems.length > 0) {
    console.error(
      `Claude skill adapters drifted from .agents/skills/:\n  ${problems.join("\n  ")}`,
    );
    console.error("Run `npm run agents:sync` to regenerate them.");
    process.exit(1);
  }
  console.log(
    `Claude skill adapters match ${canonicalNames.length} canonical skills.`,
  );
}

/** Rewrites every adapter and deletes stale generated ones so the adapter tree mirrors `.agents/skills/`. */
function sync(canonicalNames) {
  for (const name of canonicalNames) {
    mkdirSync(join(adapterRoot, name), { recursive: true });
    writeFileSync(join(adapterRoot, name, "SKILL.md"), renderAdapter(name));
  }
  for (const name of findStaleAdapters(canonicalNames))
    rmSync(join(adapterRoot, name), { recursive: true });
  console.log(`Synced ${canonicalNames.length} Claude skill adapters.`);
}

const canonicalNames = listSkillNames(canonicalRoot);
if (process.argv.includes("--check")) check(canonicalNames);
else sync(canonicalNames);
